log_dir: "checkpoint"
save_freq: 10
device: "cuda"
epochs: 100
batch_size: 64
pretrained_model: "epoch_00045.pth"
train_data: "/content/Data/train_asr.txt"
val_data: "/content/Data/train_asr.txt"


preprocess_parasm:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300
  mel_params:
    n_mels: 80

model_params:
   input_dim: 80
   hidden_dim: 256
   n_token: 178
   token_embedding_dim: 512

optimizer_params:
  lr: 0.0005
