log_dir: "checkpoint"
save_freq: 5
device: "cuda"
epochs: 100
batch_size: 8
pretrained_model: "/home/projects/styletts/Utils/ASR/epoch_00045.pth"
train_data: "Data/train_no_phones.txt"
val_data: "Data/val_no_phones.txt"


preprocess_parasm:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300
  mel_params:
    n_mels: 80

model_params:
   input_dim: 80
   hidden_dim: 256
   n_token: 178
   token_embedding_dim: 512

optimizer_params:
  lr: 0.0005
